#  -------------------------------------------------------------------------
#  Copyright (C) 2023 BMW AG
#  -------------------------------------------------------------------------
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#  -------------------------------------------------------------------------

---
include:
  - .*

exclude:
  # exclude all external
  - ^external/

  # exclude generated flatbuffers files
  - ^src/client/internal/logic/flatbuffers/

sort-order:
  # run on tests first because tests tend to take long due to googletest macros
  - pattern: /test/
    priority: 10

check-filter:
  # false positives on clang-12 related to google test matchers
  - check: clang-analyzer-cplusplus.NewDeleteLeaks
    pattern: Potential leak of memory pointed to by field 'shared'
    exclude:
      - ^tests/*
  - check: cppcoreguidelines-narrowing-conversions
    exclude:
      - ^tests/.*
  - check: cppcoreguidelines-pro-type-reinterpret-cast
    include:
      - ^src/framework/
      - ^client/
  - check: cppcoreguidelines-pro-type-vararg
    exclude:
      # ImGui uses va_args in its api
      - ^tools/ramses-scene-viewer/src/SceneViewerGui.cpp$
      - ^tools/ramses-imgui/src/ImguiWidgets.cpp$
  - check: hicpp-signed-bitwise
    exclude:
      - ^examples/ramses-example-local-dma-offscreenbuffer/src/main.cpp$
      - ^tests/integration/renderer-tests/dma-offscreen-buffer-rendering-tests/DmaOffscreenBufferTests.cpp$
  - check: modernize-avoid-c-arrays
    exclude:
      - ^tests/.*

remove-duplicate-sources: true
remove-duplicate-reports: true
filter-headers: true
