#  -------------------------------------------------------------------------
#  Copyright (C) 2023 BMW AG
#  -------------------------------------------------------------------------
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#  -------------------------------------------------------------------------

---
include:
  - .*

exclude:
  # exclude all external
  - ^external/

  # exclude generated flatbuffers files
  - ^client/logic/lib/flatbuffers/

sort-order:
  # run on tests first because tests tend to take long due to googletest macros
  - pattern: /test/
    priority: 10

check-filter:
  - check: cppcoreguidelines-pro-type-reinterpret-cast
    include:
      - ^framework/
      - ^client/
  # false positives on clang-12 related to google test matchers
  - check: clang-analyzer-cplusplus.NewDeleteLeaks
    pattern: Potential leak of memory pointed to by field 'shared'
    exclude:
      - /test/.*Test.cpp$
      - ^renderer/RendererLib/RendererLib/test/RendererSceneUpdaterTest_Resources.cpp$
      - ^renderer/RendererLib/RendererLib/test/TestSceneHelper.h$
      - ^renderer/RendererLib/RendererLib/test/RendererSceneUpdaterTest.h$
      - ^renderer/RendererLib/RendererTestCommon/RendererResourceManagerMock.cpp$
  - check: hicpp-signed-bitwise
    exclude:
      - ^examples/ramses-example-local-dma-offscreenbuffer/src/main.cpp$
      - ^integration/SandwichTests/RendererTests/DmaOffscreenBufferRenderingTests/DmaOffscreenBufferTests.cpp$
  - check: modernize-avoid-c-arrays
    exclude:
      - ^client/test/.*Test.cpp$
      - ^framework/Core/Math3d/include/Math3d
      - ^framework/.*/test/.*Test.cpp$
      - ^renderer/RendererLib/RendererLib/test/.*Test.cpp$
      - ^renderer/ramses-renderer-impl/test/.*Test.cpp$
      - ^integration/SandwichTests/RendererTests/EmbeddedCompositingTests
      - ^integration/TestContent

remove-duplicate-sources: true
remove-duplicate-reports: true
filter-headers: true
