#  -------------------------------------------------------------------------
#  Copyright (C) 2022 BMW AG
#  -------------------------------------------------------------------------
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#  -------------------------------------------------------------------------

---
- name: check versions
  shell: |
    set -e
    ./ci/scripts/check_versions.sh
  args:
    executable: /bin/bash
    chdir: "{{ zuul.project.src_dir }}"
