#  -------------------------------------------------------------------------
#  Copyright (C) 2020 BMW AG
#  -------------------------------------------------------------------------
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#  -------------------------------------------------------------------------

---
- name: install python apt packages
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - python3-setuptools
    - python3-venv

- name: Create virtualenv and update pip
  shell: |
    set -e
    /usr/bin/python3 -m venv {{ rlogic_venv }}
    {{ rlogic_venv }}/bin/pip install --upgrade pip setuptools wheel
  args:
    executable: /bin/bash

- name: install pip packages
  pip:
    name:
      - wheel
      - github3.py==1.3.0
    virtualenv: "{{ rlogic_venv }}"
    virtualenv_command: "/usr/bin/python3 -m venv"
