name: Test

# This is derived from the standard CMake template for github actions.
# For more details on the settings used, have a look at the template in the marketplace

# Only pushes and PRs against protected branches are built
on:
  pull_request:
    branches:
      - master
jobs:
  publish_docs:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Create Build Environment
      run: |
        cmake -E make_directory ${{runner.workspace}}/build
        sudo apt install graphviz doxygen

    - name: Build docs
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake $GITHUB_WORKSPACE \
            -Dramses-sdk_BUILD_HEADLESS_SHARED_LIB=ON \
            -Dramses-sdk_BUILD_FULL_SHARED_LIB=OFF \
            -Dramses-sdk_ENABLE_DEFAULT_WINDOW_TYPE=OFF \
            -Dramses-sdk_BUILD_TESTS=OFF \
            -Dramses-sdk_BUILD_EXAMPLES=OFF \
            -Dramses-sdk_BUILD_DEMOS=OFF \
            -Dramses-sdk_BUILD_TOOLS=OFF

        cmake --build . --target doc
